### ISSUE TITLE
Motion Tracker stealing my ears for it self

### ISSUE THREAD

**Issue by VanilaBOI** [CyanBlob/LethalCompany_MotionTracker#2] opened 2023-12-07 19:20 UTC
Just wanted to say I love the Mod, it works so well with it only showing things that give of vibrations and only if they move great job.

My Problem is that when I use it I hear everything from the trackers point of view.
For example when Im not holding it I either hear from my left or right ear.
And When I drop it and go away I hear myself walk away and than I hear nothing.

**Comment by CyanBlob** [comment] 2023-12-07 19:40
This is bizarre. I can't imagine why it would be happening. Does this happen on multiplayer, single player, or both? Does it happen every time?

**Comment by Entity378** [comment] 2023-12-09 23:47
I confirm, I encountered the same type of problem. Basically all the audio is played by the person holding the motion tracker, if the person is not holding it the audio is played in the last position in which the motion tracker was held.

**Comment by CyanBlob** [comment] 2023-12-10 06:40
Are you both using version 0.1.3? I'll try to figure this out tomorrow

**Comment by Entity378** [comment] 2023-12-10 12:18
yes, regardless the problem is present in all versions of the mod.

**Comment by CyanBlob** [comment] 2023-12-10 19:13
This is *hopefully* fixed in v0.1.4. Can y'all update and let me know?

**Comment by Entity378** [comment] 2023-12-10 19:58
It's still buggy

**Comment by Entity378** [comment] 2023-12-14 13:27
I tested the latest version of the mod (1.0.0) and it seems that the bug is fixed. I only tried in singleplayer but I think the issue can be considered solved. You can close this issue.

**Comment by CyanBlob** [comment] 2023-12-14 17:16
Thanks for the confirmation! I'll close this issue.

**Closed** 2023-12-14 17:17 UTC
